In [2]:
from dataclasses import field
import ratelimit
import time
import gspread
from fontTools.subset import subset
from ratelimit import limits
%matplotlib ipympl
import ipywidgets as widgets
from utilities import find_latest_file, cleanup_str, to_csv_file
from loggingUtil import setup_logging
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.widgets as wg
import geopandas as gpd
import folium
from reformatData import reformate_data_and_clean_it
import collectDataFromSheets
import os
log = setup_logging("JUP LOG")
from fuzzywuzzy import process
pd.set_option('future.no_silent_downcasting', True)

In [ ]:
df = find_latest_file("Full")
gdf = gpd.GeoDataFrame(df, crs="EPSG:4326", geometry=gpd.points_from_xy(x=df["Longitude"], y=df["Latitude"]))

In [ ]:
# gdf.explore(markers="v", column="Year", )

In [ ]:
gdf = gpd.read_file("pdf.geojson")
gdf.set_crs(epsg=4326, inplace=True, allow_override=True)
m = gdf.explore(fill=False, name="County Outlines", legend=True, )
folium.LayerControl().add_to(m)

"

In [ ]:
def get_widget_data(year_range_slider, apple_names_p_drops, min_fair_threshold_dropdown):
    year_max = year_range_slider.value[1]
    year_min = year_range_slider.value[0]
    apple_names = []
    if not check_rand:
        for apple_dropdown in apple_names_p_drops:
            apple_names.append(apple_dropdown.value)
    else:
        apple_names = apple_names_p_drops

    df = find_latest_file("Full")

    df = df.merge(df.groupby("Year")["Event"].count().rename("Number of Events in a Year"), how="left", on="Year")

    df = df.loc[df["Number of Events in a Year"] >= min_fair_threshold_dropdown.value]

    if len(apple_names) > 0:
        df = df.loc[df["Use Name"].isin(apple_names)]

    nf = df.loc[df["Year"] <= year_max]
    nf = nf.loc[nf['Year'] >= year_min]

    if check_rand.value:
        nf = nf.loc[df["Use Name"].isin(nf.groupby("Use Name")["Year"].count().sort_values(ascending=False).head(number_of_apples.value).reset_index()["Use Name"])]

    for apple_name in apple_names:
        nf = nf.merge(nf.loc[nf["Use Name"] == apple_name].groupby("Year")["Event"].count().rename(f"# {apple_name} fair"), how="left", on="Year")
        nf[f"% in fairs"] = nf[f"# {apple_name} fair"] / nf["Number of Events in a Year"] * 100
    gdf = gpd.GeoDataFrame(nf, crs="EPSG:4326", geometry=gpd.points_from_xy(x=nf["Longitude"], y=nf["Latitude"]))
    return gdf

In [ ]:
df = find_latest_file("Full")
year_slider = widgets.IntRangeSlider(min=df['Year'].min(), max=df['Year'].max(), value=[df['Year'].min(), df['Year'].max()])
number_of_apples = widgets.IntText(min=0, max=len(df["Use Name"].unique()), value=2, description="Number of apples")
min_fair_threshold = widgets.IntText(min=0, value=10, description="Fair Threshold")
check_rand = widgets.Checkbox(description="random", value=True)
display(year_slider, number_of_apples, min_fair_threshold, check_rand)

In [ ]:
def get_most_common_apples():
    nf = find_latest_file("Full")
    return nf.groupby("Use Name")["Year"].count().sort_values(ascending=False).head(number_of_apples.value).reset_index()["Use Name"]

In [ ]:
apples_dropdowns = []
if not check_rand.value:
    for i in range(number_of_apples.value):
        apples_dropdowns.append(widgets.Dropdown(options=df["Use Name"].unique(), value="baldwin", description=f"Select Apple Type[{i + 1}]"))
    for dropdown in apples_dropdowns:
       display(dropdown)
else:
    apples_dropdowns = get_most_common_apples()

In [ ]:
nf = get_widget_data(year_slider, apples_dropdowns, min_fair_threshold)
nf

In [ ]:
apples, sources = reformate_data_and_clean_it()

In [217]:

ds= sources.copy()

ds.drop(columns=["Event"], inplace=True)
ds.rename({"county name": "County", "event name":"Event"}, axis=1, inplace=True)
ds = ds.apply(lambda column: column.apply(cleanup_str))
ds["Year"] = sources["Year"].astype(int)


# source dates
def _cleanup_source_dates(row_in_source_date):
    try:
        return pd.to_datetime(row_in_source_date, format="%m/%d/%Y")
    except ValueError:
        return str(row_in_source_date) + ": Error Here"
ds["Source Date"] = ds["Source Date"].replace("unknown", pd.NaT)
ds["Source Date"] = ds["Source Date"].apply(_cleanup_source_dates).fillna(pd.NaT)
errors_in_sources = ds.loc[ds["Source Date"].str.contains(": Error Here").fillna(False)]
ds.loc[ds["Source Date"].isin(errors_in_sources["Source Date"]), "Source Date"] = pd.NaT
ds["Source Date"] = ds["Source Date"].astype("datetime64[ns]")


# page numbers
PAGE_NUMBER_COLUMNS = ["Page #1", "Page #2", "Page #3"]
ds["Page"] = ds["Page"].str.replace("&", "")
ds["Page"] = ds["Page"].str.replace(" ", "")
ds[PAGE_NUMBER_COLUMNS] =  ds["Page"].str.split(pat=",", expand=True)
ds.loc[:,PAGE_NUMBER_COLUMNS] = ds.loc[:, PAGE_NUMBER_COLUMNS].apply(lambda column: column.replace("unknown", np.nan), axis=0)
ds.drop(columns=["Page"], inplace=True)

# notes premiums and des
NOTES_COLUMNS = ["Apple Mentioned in Premiums", "Apple Mentioned in Description"]
ds["Notes"] = ds["Notes"].replace("unknown", np.nan).replace("des. & pre.", "des. & prem.")
ds[NOTES_COLUMNS[0]] = ds["Notes"].str.contains("prem")
ds[NOTES_COLUMNS[1]] = ds["Notes"].str.contains("des")
ds.drop(columns=["Notes"], inplace=True)

PER_SOURCE_COLUMNS = ["Source", "Source Date", "Page #1", "Page #2", "Page #3","Additional Notes", "Apple Mentioned in Premiums", "Apple Mentioned in Description"]
INDEX_COLUMNS = ["Year", "County", "Event"]
ds["merged sources"] = ds.loc[:,PER_SOURCE_COLUMNS].apply(lambda row: "|".join(row.astype(str)), axis=1)
ds.drop(columns=PER_SOURCE_COLUMNS, inplace=True)
ds["rank"] = ds.groupby(INDEX_COLUMNS)["merged sources"].rank()
pivot_table_for_sources = ds.pivot(columns="rank", values="merged sources", index=INDEX_COLUMNS)
for col in pivot_table_for_sources.columns:
    pivot_table_for_sources[[type + " of Source: " + str(int(col)) for type in PER_SOURCE_COLUMNS]] = pivot_table_for_sources[col].str.split("|", expand=True)
pivot_table_for_sources.drop(columns=[1.0,2.0,3.0,4.0], inplace=True)
pivot_table_for_sources.reset_index(inplace=True)

# check dups
duped_sources = pivot_table_for_sources.loc[pivot_table_for_sources.duplicated(keep=False)]
if not duped_sources.empty:
    log.Error(f"duplicated rows in sources"
              f" dropping them")
    to_csv_file(path="debugInfo", df=duped_sources, name="DebugFile-DupedSources")

    pivot_table_for_sources.drop_duplicates(keep="first", inplace=True)

Empty DataFrame
Columns: [Year, County, Event, Source of Source: 1, Source Date of Source: 1, Page #1 of Source: 1, Page #2 of Source: 1, Page #3 of Source: 1, Additional Notes of Source: 1, Apple Mentioned in Premiums of Source: 1, Apple Mentioned in Description of Source: 1, Source of Source: 2, Source Date of Source: 2, Page #1 of Source: 2, Page #2 of Source: 2, Page #3 of Source: 2, Additional Notes of Source: 2, Apple Mentioned in Premiums of Source: 2, Apple Mentioned in Description of Source: 2, Source of Source: 3, Source Date of Source: 3, Page #1 of Source: 3, Page #2 of Source: 3, Page #3 of Source: 3, Additional Notes of Source: 3, Apple Mentioned in Premiums of Source: 3, Apple Mentioned in Description of Source: 3, Source of Source: 4, Source Date of Source: 4, Page #1 of Source: 4, Page #2 of Source: 4, Page #3 of Source: 4, Additional Notes of Source: 4, Apple Mentioned in Premiums of Source: 4, Apple Mentioned in Description of Source: 4]
Index: []

[0 rows x 35 columns]

In [58]:
ds

["Source Date"]

['Source Date']

In [14]:
source = find_latest_file("AppleNamesCleaned")
source.loc[:,["Event", "Year"]].drop_duplicates()

                                Event  Year
0                       oxford county  1912
1                       oxford county  1916
2      gorham & standish farmers club  1880
3                           otisfield  1892
4               north franklin county  1914
...                               ...   ...
22524                sagadahoc county  1883
25341                     york county  1849
26148          pleasant valley grange  1907
26157               north knox county  1908
26452           sheepscot lake grange  1947

[1258 rows x 2 columns]

In [11]:
source.loc[~source["Event"].duplicated()]

,Additional Notes,Event,Location,Notes,Page,Source,Source Date,Year,county name,event name
0,NaN,Androscoggin county,NaN,Description,3,Lewiston Evening Journal,10/06/1875,1875.0,androscoggin,androscoggin county
10,NaN,Androscoggin Grange,Greene,Premiums,2,Lewiston Evening Journal,10/04/1899,1899.0,androscoggin,androscoggin grange
27,NaN,Durham,Durham,Premiums,7,Lewiston Wednesday Journal,10/10/1888,1888.0,androscoggin,durham
33,NaN,Excelsior Grange,East Poland,Premiums,10,Lewiston Daily Sun,10/10/1924,1924.0,androscoggin,excelsior grange
34,NaN,Leeds,Leeds,Des. & Prem.,4,Lewiston Evening Journal,10/21/1886,1886.0,androscoggin,leeds
...,...,...,...,...,...,...,...,...,...,...
1362,NaN,Shapleigh & Acton,Acton,Premiums,2,Biddeford Weekly Journal,10/16/1889,1889.0,york,shapleigh & acton
1392,NaN,South Waterboro Grange,South Waterboro,Premiums,8,The Weekly Record,11/07/1912,1912.0,york,south waterboro grange
1393,NaN,Waterboro,Waterboro,Premiums,6,Sanford Tribune & Advocate,10/08/1925,1925.0,york,waterboro
1398,NaN,York county,Limerick,Description,2,The Union,10/19/1849,1849.0,york,york county
1417,NaN,York county Farm Bureau Meeting,NaN,Premiums,7,Biddeford Weekly Journal,11/14/1919,1919.0,york,york county farm bureau meeting